//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import java.util.Date;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Cours extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private Sale sale;
	private Date dateCour;
	private int duree;
	private Matiere matiere;
	private Promotion promotion;

	public Cours() {

	}

	public Cours(Date dateCour, int duree) {
		super();
		this.dateCour = dateCour;
		this.duree = duree;
	}


	@Override
	public String toString() {
		return String.format("Cours[%s,%s,%s,%s,%s]",dateCour,duree);
	}
	
	public Sale getSale() {
		return this.sale;
	}

	public void setSale(Sale sale) {
		this.sale = sale;
	}

	public Date getDateCour() {
		return this.dateCour;
	}

	public void setDateCour(Date dateCour) {
		this.dateCour = dateCour;
	}

	public int getDuree() {
		return this.duree;
	}

	public void setDuree(int duree) {
		this.duree = duree;
	}

	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	

	

}
