//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

public class EtudiantEvalu extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private double note;
	private Evaluation evaluation;
	private Boolean absence;
	private String motif;
	private Etudiant etudiant;

	public EtudiantEvalu() {

	}

	public EtudiantEvalu(double note, Evaluation evaluation, Boolean absence, String motif, Etudiant etudiant) {
		super();
		this.note = note;
		this.evaluation = evaluation;
		this.absence = absence;
		this.motif = motif;
		this.etudiant = etudiant;
	}

	@Override
	public String toString() {
		return String.format("EtdiantEvalu[%s,%s,%s,%s,%s]", etudiant.id, evaluation.id, note, absence, motif);
	}

	public Double getNote() {
		return this.note;
	}

	public Boolean isAbsence() {
		return this.absence;
	}

	public void setAbsence(Boolean absence) {
		this.absence = absence;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Evaluation getEvaluation() {
		return evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	public Boolean getAbsence() {
		return absence;
	}

	public void setNote(double note) {
		this.note = note;
	}

}
