//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

public class EtudiantCours extends AbstractEntity {
	private static final long serialVersionUID = 1L;
    
	private boolean absence;

	private String motif;
	private Cours cours;
	private Etudiant etudiant;


	public EtudiantCours() {

	}

	
	public EtudiantCours(boolean absence, String motif) {
		super();
		this.absence = absence;
		this.motif = motif;
	}


	

	
	public EtudiantCours(boolean absence, String motif, Cours cours, Etudiant etudiant) {
		super();
		this.absence = absence;
		this.motif = motif;
		this.cours = cours;
		this.etudiant = etudiant;
	}


	@Override
	public String toString() {
		return String.format("EtudiantCours[%s,%s,%s,%s]", cours.getId(),etudiant.getId(),absence, motif);
	}

	

	public boolean isAbsence() {
		return absence;
	}


	public void setAbsence(boolean absence) {
		this.absence = absence;
	}


	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Cours getCours() {
		return cours;
	}

	public void setCours(Cours cours) {
		this.cours = cours;
	}	

}
