//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

public class Promotion extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	// Promotion est lié à filiere
	private Filiere filiere;

	private String libelle;
	private String description;

	public Promotion() {

	}

	

	public Promotion(Filiere filiere, String libelle, String description) {
		super();
		this.filiere = filiere;
		this.libelle = libelle;
		this.description = description;
	}



	@Override
	public String toString() {
		return String.format("Promotion[%s,%s]", filiere, libelle);
	}

	public Filiere getFiliere() {
		return this.filiere;
	}

	public void setFiliere(Filiere filiere) {
		this.filiere = filiere;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}



}
