/// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class Sale extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private String descript;

	private String nomSale;

	public Sale() {

	}
	
	
	
	public Sale(String descript, String nomSale) {
		super();
		this.descript = descript;
		this.nomSale = nomSale;
	}



	@Override
	public String toString() {
		return String.format("Sale[%s]",nomSale);
	}

	public String getDescript() {
		return this.descript;
	}

	public void setDescript(String descript) {
		this.descript = descript;
	}

	public String getNomSale() {
		return this.nomSale;
	}

	public void setNomSale(String nomSale) {
		this.nomSale = nomSale;
	}

}
