//
// This file was generated by the JPA Modeler
//
package ci.kossovo.ecole.entity;

import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class TypeEvaluation extends AbstractEntity {
	private static final long serialVersionUID = 1L;

	private String libelle;

	public TypeEvaluation() {

	}

	public TypeEvaluation(String libelle) {
		super();
		this.libelle = libelle;
	}

	@Override
	public String toString() {
		return String.format("TypeEvalution[%s]", libelle);
	}

	public String getLibelle() {
		return libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
